volumes:
  pgdata:
    driver: local
    driver_opts:
      type: none
      device: ./data/postgres
      o: bind

networks:
  pong:
    driver: bridge

services:
  user_api:
    container_name: user_api
    build:
      context: ./user_service
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - pong
    ports:
      - '8000:8000'
    command: >
      bash -c "sleep 5 && python manage.py makemigrations user_api && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - '5432:5432'
    networks:
      - pong
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
